TrajectoryPlannerROS:
  max_vel_x: 0.75  #2.25
  min_vel_x: 0.0   #-2.25
  max_vel_y: 0.75  #0.75
  min_vel_y: 0.0
  max_rotational_vel: 20.0
  min_in_place_rotational_vel: 20.0
  min_in_place_vel_theta: 20.0  #-1.0 #-20.0
  max_vel_theta: 10.0  #0.5 #10.0 #5.5
  min_vel_theta: -10.0 #-10.0 #-5.5
  acc_lim_theta: 10.2  #0.2 #10.2 #5.0
  acc_lim_x: 0.5  #1.2
  acc_lim_y: 0.5  #1.2
  holonomic_robot: true
  vx_samples: 10
  vtheta_samples: 20



