DWAPlannerROS:

# Robot Configuration Parameters
  max_vel_x: 0.75 #2.25
  min_vel_x: -0.75 #-2.25 

  max_vel_y: 0.75
  min_vel_y: -0.75

  # The velocity when robot is moving in a straight line
  max_trans_vel:  1.0 #1.0 #0.18
  min_trans_vel:  0.03 #0.6  #0.05
  #trans_stopped_vel: 0.55 

  max_rot_vel: 0.0  #20
  min_rot_vel: 0.0  #5
  #rot_stopped_vel: 0 #1.9

  acc_lim_x: 2.5 #2.0 # increased acceleration to compensate low initial velocities
  acc_lim_theta: 0.0 #10.2
  acc_lim_y: 2.5

# Goal Tolerance Parameters
  yaw_goal_tolerance: 0.05  # 0.2
  xy_goal_tolerance: 0.5 # 0.50
  # latch_xy_goal_tolerance: false

# Forward Simulation Parameters
  sim_time: 4.0       # 2.0
  vx_samples: 11       # 3
  vy_samples: 11       # diff drive robot, there is only one sample
  vtheta_samples: 0  # 30
  sim_granularity: 0.025 #0.0125  # 0.3


# Trajectory Scoring Parameters
  path_distance_bias: 32.0 # 32.0   - weighting for how much it should stick to the global path plan
  goal_distance_bias: 24.0      # 24.0   - wighting for how much it should attempt to reach its goal
  occdist_scale: 0.005            # 0.005   - weighting for how much the controller should avoid obstacles
  
# Oscillation Prevention Parameters
  oscillation_reset_dist: 0.05 #500  # 0.05   - how far to travel before resetting oscillation flags

# Debugging
  publish_traj_pc : true
  publish_cost_grid_pc: true
  global_frame_id: map #map  


