local_costmap:
  global_frame: map #map
  robot_base_frame: /base_link
  update_frequency: 5.0 #1.0 2.0 #5.0
  publish_frequency: 2.0 #5.0 2.0
  static_map: false
  rolling_window: true
  width: 10.0
  height: 10.0
  origin_x: -5.0
  origin_y: -5.0
  resolution: 0.005
  transform_tolerance: 1.0 #0.5 
  planner_frequency: 10.0 #10.0 
  planner_patiente: 5.0 #10.0 
  max_obstacle_height: 10.0
  min_obstacle_height: 0.0

plugins:
  - {name: obstacles_laser,           type: "costmap_2d::ObstacleLayer"}
  - {name: inflation,                 type: "costmap_2d::InflationLayer"}



