TebLocalPlannerROS:

# Trajectory
  
teb_autosize: True
dt_ref: 0.3
dt_hysteresis: 0.1
global_plan_overwrite_orientation: false
allow_init_with_backwards_motion: true
max_global_plan_lookahead_dist: 3.0
feasibility_check_no_poses: 5


# Robot
acc_lim_x: 2.5
acc_lim_y: 2.5
acc_lim_theta: 0.0
max_vel_x: 0.75
max_vel_y: 0.75
max_vel_x_backwards: 0.75
max_vel_theta: 0.0
min_turning_radius: 0.0 # omni-drive robot (can turn on place!)

cmd_angle_instead_rotvel: true

footprint_model:
   type: "point"

# Optimization

 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1
 weight_max_vel_x: 2
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 1000
 weight_kinematics_forward_drive: 0
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 1
 weight_obstacle: 50
 weight_dynamic_obstacle: 10 # not in use yet
alternative_time_cost: False # not in use yet

