TebLocalPlannerROS:

# Trajectory
  
teb_autosize: True
dt_ref: 0.3
dt_hysteresis: 0.1
#global_plan_overwrite_orientation true
allow_init_with_backwards_motion: true
max_global_plan_lookahead_dist: 3.0
feasibility_check_no_poses: 5


# Robot
acc_lim_x: 2.5
acc_lim_y: 2.5
acc_lim_theta: 2.5
max_vel_x: 0.75
max_vel_y: 0.75
max_vel_x_backwards: 0.75
max_vel_theta: 0.3
min_turning_radius: 0.0 # omni-drive robot (can turn on place!)

cmd_angle_instead_rotvel: true

footprint_model:
   type: "point"

